# Site settings
title: absessive - the blog
email: absessive@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of interesting Ruby/iOS features or code snippets I've found interesting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://absessive.github.io" # the base hostname & protocol for your site
twitter_username: absessive
github_username:  absessive

# Build settings
markdown: kramdown
